Update utils.ts
Fixes two issues:

oot-BCCP3GJZ.js:12 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startsWith')

and urlString.startsWith is not a function

This occurs because the fetch behaviour is overridden and URL is a valid parameter to fetch. Sometimes the URL is not present and this function would break that code as well.